name: My First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
      - run: pwd
      - run: sleep 100
  anotherjob:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 200
  anotheranotherjob:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 50
