name: My First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
      - run: pwd
      - uses: nicruo/novemberactionrepo@main
