name: My First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
      - run: pwd
      - uses: nicruo/novemberactionrepo@main

  deploydev:
    runs-on: ubuntu-latest
    environment: dev
    needs: firstjob
    steps:
      - run: echo app deployed

  deployprod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploydev
    steps:
      - run: echo app deployed
